# ─── FUENTE ──────────────────────────────────────────
font_family           JetBrainsMono Nerd Font
font_size             11.0
adjust_line_height    110%

# ─── COLORES ─────────────────────────────────────────
background            #0f0f0f
foreground            #d0d0d0
background_opacity    0.88

cursor                #d0d0d0
selection_background  #2e2e2e
selection_foreground  #e8e8e8

color0  #0f0f0f
color8  #3a3a3a
color1  #b05c5c
color9  #c46a6a
color2  #6a9e5a
color10 #7ab06a
color3  #a89050
color11 #baa060
color4  #5878a8
color12 #6888b8
color5  #8860a0
color13 #9870b0
color6  #4e9090
color14 #5ea0a0
color7  #c8c8c8
color15 #e8e8e8

# ─── CURSOR ──────────────────────────────────────────
cursor_shape          beam
cursor_beam_thickness 1.5
cursor_blink_interval 0

# ─── COMPORTAMIENTO ──────────────────────────────────
window_padding_width        0
confirm_os_window_close     0
enable_audio_bell           no
scrollback_lines            10000
copy_on_select              yes
strip_trailing_spaces       smart
focus_follows_mouse         yes

# ─── URLS ────────────────────────────────────────────
url_style                   straight
open_url_with               default
detect_urls                 yes

# ─── DECORACIÓN ──────────────────────────────────────
hide_window_decorations     yes
window_border_width         0

# ─── ATAJOS ──────────────────────────────────────────
map ctrl+c      copy_or_interrupt
map ctrl+v      paste_from_clipboard
map ctrl+shift+v paste_from_selection

map ctrl+equal  change_font_size all +1.0
map ctrl+minus  change_font_size all -1.0
map ctrl+0      change_font_size all 0

map ctrl+shift+f launch --type=overlay --stdin-source=@screen_scrollback /usr/bin/fzf --no-sort --no-mouse -i -m --tac | xargs -I{} kitty @ send-text {}

map ctrl+shift+h show_scrollback

map ctrl+shift+u open_url_with_hints
