general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = playerctl -a status 2>/dev/null | grep -q "Playing" || loginctl lock-session
}

listener {
    timeout = 360
    on-timeout = playerctl -a status 2>/dev/null | grep -q "Playing" || hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 2040
    on-timeout = notify-send -u critical -t 55000 "Suspendiendo en 1 minuto" "Sin actividad por 34 min"
}

listener {
    timeout = 2100
    on-timeout = systemctl poweroff
}